### PR TITLE
fix!: Raise error when adding duplicate email address in Personalizations

### LINKED ISSUE #436: Checking duplicate email address specified into personalizations as case insensitive
### Issue Summary
SendGrid says: 
> All of the recipients in a single personalization object (either in the to, cc, or bcc fields) will see the same email, as defined by the data in that personalization, as such we do not allow duplicate emails between these 3 arrays in a single personalization.

ref: https://sendgrid.com/docs/for-developers/sending-email/personalizations/

And https://github.com/sendgrid/sendgrid-csharp implements case insensitive comparison method.
https://github.com/sendgrid/sendgrid-csharp/blob/23e4f6425c2d8546f1c8ca84bc2c93e5c5f9c1df/src/SendGrid/Helpers/Mail/Model/EmailAddress.cs#L91

I want to get implemented method that checking duplicate email address specified into personalizations as case insensitive.

### Steps to Reproduce
1. specify duplicate email address to "to addresses".
2. request to send email
3. get 400 error that says "Each unique email address in the personalizations array should only be included once. You have included [email address] more than once."

### Exception/Log
I have checked how SendGrid behaves to duplicated email addresses.
Then, SendGrid returned 2 errors for following request body.

Request Body
```
{
  "personalizations": [
    {
      "to": [
        {
          "email": "test@example.com"
        },
        {
          "email": "TEST@example.com"
        }
      ],
      "cc": [
        {
          "email": "test@foobar.com"
        },
        {
          "email": "TEST@foobar.com"
        }
      ],
      "subject": "Hello, World!"
    }
  ],
  "from": {
    "email": "test@sender.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, World!"
    }
  ]
}
```

Returned error
```
{
  "errors": [
    {
      "message": "Each email address in the personalization block should be unique between to, cc, and bcc. We found the first duplicate instance of [test@example.com] in the personalizations.0.to field.",
      "field": "personalizations.0",
      "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.recipient-errors"
    },
    {
      "message": "Each email address in the personalization block should be unique between to, cc, and bcc. We found the first duplicate instance of [test@foobar.com] in the personalizations.0.cc field.",
      "field": "personalizations.0",
      "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.recipient-errors"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by Pranc1ngPegasus**
fix: Checking duplicate email address specified into personalizations as case insensitive

# Fixes #436

Checking duplicate email address specified into personalizations as case insensitive

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

### CODE REVIEW

**Review by eshanholtz — APPROVED** [review]
Thanks for the contribution!

File: lib/sendgrid/helpers/mail/personalization.rb [hunk 1]
```diff
@@ -63,5 +69,19 @@ def to_json(*)
         'send_at' => send_at
       }.delete_if { |_, value| value.to_s.strip == '' || value == [] || value == {} }
     end
+
+    private
+
+    def duplicate?(addition)
+      additional_email = addition.email.downcase
+
+      [@tos, @ccs, @bccs].flatten.each do |elm|
```
Comment (childish-sambino) [inline lib/sendgrid/helpers/mail/personalization.rb:78]: SendGrid allows for duplicates across email groups. E.g., I can `to` and `bcc` the same address without issue. I don't think this library should add _more_ checks.

**Review by childish-sambino — COMMENTED** [review]
Is this really a breaking change that warrants a MV roll?

File: lib/sendgrid/helpers/mail/personalization.rb (hunk 1 above)
Comment (eshanholtz) [reply lib/sendgrid/helpers/mail/personalization.rb:78]: According to the [docs](https://sendgrid.com/docs/for-developers/sending-email/personalizations/) SendGrid does not allow duplicates across `to`/`cc`/`bcc` within a single personalization
